version: "3.7"
services:
  app-service:
    image: ${APP_NAME}:1.0.0
    container_name: ${APP_NAME}_1
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/${APP_NAME}
      - /${APP_NAME}/node_modules
    external_links:
      - ${LINK_REDIS}:${LINK_REDIS}
    networks:
      - default
networks:
  default:
    external: true
    name: boilerplate-microservice-network
